src/Entity/Campus.php
<?php

namespace App\Entity;

use App\Repository\CampusRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CampusRepository::class)]
class Campus
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $campus_name = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\OneToMany(targetEntity: User::class, mappedBy: 'campus', orphanRemoval: true)]
    private Collection $users;

    /**
     * @var Collection<int, Sortie>
     */
    #[ORM\OneToMany(targetEntity: Sortie::class, mappedBy: 'campus')]
    private Collection $sorties;

    public function __construct()
    {
        $this->users = new ArrayCollection();
        $this->sorties = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCampusName(): ?string
    {
        return $this->campus_name;
    }

    public function setCampusName(string $campus_name): static
    {
        $this->campus_name = $campus_name;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): static
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->setCampus($this);
        }

        return $this;
    }

    public function removeUser(User $user): static
    {
        if ($this->users->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getCampus() === $this) {
                $user->setCampus(null);
            }
        }

        return $this;
    }

    public function addSortie(Sortie $sortie): static
    {
        if (!$this->sorties->contains($sortie)) {
            $this->sorties->add($sortie);
            $sortie->setCampus($this);
        }

        return $this;
    }

    public function removeSortie(Sortie $sortie): static
    {
        if ($this->sorties->removeElement($sortie)) {
            if ($sortie->getCampus() === $this) {
                $sortie->setCampus(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->getCampusName();
    }


}

src/Entity/City.php
<?php

namespace App\Entity;

use App\Repository\CityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CityRepository::class)]
class City
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 40)]
    private ?string $city_name = null;

    #[ORM\Column(length: 5)]
    private ?string $postal_code = null;

    /**
     * @var Collection<int, Place>
     */
    #[ORM\OneToMany(targetEntity: Place::class, mappedBy: 'city', orphanRemoval: true)]
    private Collection $places;

    // Ajoutez ces deux lignes avec vos autres propriétés
    #[ORM\Column(length: 255, nullable: true)]
    private ?string $latitude = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $longitude = null;

    public function __construct()
    {
        $this->places = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCityName(): ?string
    {
        return $this->city_name;
    }

    public function setCityName(string $city_name): static
    {
        $this->city_name = $city_name;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): static
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    /**
     * @return Collection<int, Place>
     */
    public function getPlaces(): Collection
    {
        return $this->places;
    }

    public function addPlace(Place $place): static
    {
        if (!$this->places->contains($place)) {
            $this->places->add($place);
            $place->setCity($this);
        }

        return $this;
    }

    public function removePlace(Place $place): static
    {
        if ($this->places->removeElement($place)) {
            // set the owning side to null (unless already changed)
            if ($place->getCity() === $this) {
                $place->setCity(null);
            }
        }

        return $this;
    }

    public function getLatitude(): ?string
    {
        return $this->latitude;
    }

    public function setLatitude(?string $latitude): static
    {
        $this->latitude = $latitude;
        return $this;
    }

    public function getLongitude(): ?string
    {
        return $this->longitude;
    }

    public function setLongitude(?string $longitude): static
    {
        $this->longitude = $longitude;
        return $this;
    }

}

src/Entity/Place.php
<?php

namespace App\Entity;

use App\Repository\PlaceRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: PlaceRepository::class)]
class Place
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 40)]
    #[Assert\NotBlank(message: 'Le nom du lieu est obligatoire.')]
    private ?string $place_name = null;

    #[ORM\Column(length: 40, nullable: true)]
    #[Assert\NotBlank(message: 'Le nom de la rue est obligatoire.')]
    private ?string $street = null;

    #[ORM\Column(nullable: true)]
    private ?float $latitude = null;

    #[ORM\Column(nullable: true)]
    private ?float $longitude = null;

    #[ORM\OneToMany(targetEntity: Sortie::class, mappedBy: 'place', orphanRemoval: true)]
    private Collection $sorties;

    #[ORM\ManyToOne(inversedBy: 'places')]
    #[ORM\JoinColumn(nullable: false)]
    private ?City $city = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPlaceName(): ?string
    {
        return $this->place_name;
    }

    public function setPlaceName(string $place_name): static
    {
        $this->place_name = $place_name;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): static
    {
        $this->street = $street;

        return $this;
    }

    public function getLatitude(): ?float
    {
        return $this->latitude;
    }

    public function setLatitude(?float $latitude): static
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function getLongitude(): ?float
    {
        return $this->longitude;
    }

    public function setLongitude(?float $longitude): static
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function __toString(): string
    {
        return $this->getPlaceName() ?? 'Unknown place';
    }

}

src/Entity/Status.php
<?php

namespace App\Entity;

use App\Repository\StatusRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: StatusRepository::class)]
class Status
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 20)]
    private ?string $status_label = null;

    /**
     * @var Collection<int, Sortie>
     */
    #[ORM\OneToMany(targetEntity: Sortie::class, mappedBy: 'status', orphanRemoval: true)]
    private Collection $sorties;

    public function __construct()
    {
        $this->sorties = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatusLabel(): ?string
    {
        return $this->status_label;
    }

    public function setStatusLabel(string $status_label): static
    {
        $this->status_label = $status_label;

        return $this;
    }

    /**
     * @return Collection<int, Sortie>
     */
    public function getSorties(): Collection
    {
        return $this->sorties;
    }

    public function addSortie(Sortie $sortie): static
    {
        if (!$this->sorties->contains($sortie)) {
            $this->sorties->add($sortie);
            $sortie->setStatus($this);
        }

        return $this;
    }

    public function removeSortie(Sortie $sortie): static
    {
        if ($this->sorties->removeElement($sortie)) {
            // set the owning side to null (unless already changed)
            if ($sortie->getStatus() === $this) {
                $sortie->setStatus(null);
            }
        }

        return $this;
    }
}

src/Form/SortieType.php
<?php

namespace App\Form;

use App\Entity\Campus;
use App\Entity\Place;
use App\Entity\Sortie;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class SortieType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {

        $builder
            ->add('name', TextType::class, [
                'label' => 'Nom de la sortie',
                'required' => false,
                'attr' => [
                    'placeholder' => 'Entrez le nom de la sortie',
                    'class' => 'form-control rounded-lg'
                ]
            ])
            ->add('startDatetime', DateTimeType::class, [
                'label' => 'Date et heure de la sortie',
                'html5' => true,
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control rounded-lg'
                ]
            ])
            ->add('duration', NumberType::class, [
                'label' => 'Durée (en minutes)',
                'attr' => [
                    'placeholder' => 'ex: 60 pour 1h',
                    'class' => 'form-control rounded-lg'
                ]
            ])
            ->add('registrationDeadline', DateTimeType::class, [
                'label' => "Date limite d'inscription",
                'html5' => true,
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control rounded-lg'
                ]
            ])
            ->add('maxRegistrations', NumberType::class, [
                'label' => "Nombre maximum d'inscriptions",
                'attr' => [
                    'placeholder' => 'ex: 10',
                    'class' => 'form-control rounded-lg'
                ]
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Description de la sortie',
                'attr' => [
                    'placeholder' => 'Détails, instructions, etc.',
                    'class' => 'form-control rounded-lg'
                ]
            ])
            ->add('photoUrl', FileType::class, [
                'label' => 'Image de la sortie',
                'required' => false,
                'mapped' => false,
                'attr' => [
                    'placeholder' => 'Lien vers une image (optionnel)',
                    'class' => 'form-control rounded-lg',
                    'accept' => 'image/*'
                ],
                'constraints' => [
                    new File([
                        'maxSize' => '1024K', // Taille maximale du fichier
                        'maxSizeMessage' => 'Le fichier ne doit pas dépasser 1 Mo',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                            'image/jpg',
                        ],
                        'mimeTypesMessage' => 'Format de fichier non valide, veuillez télécharger une image au format JPEG, JPG ou PNG.',
                    ])
                ]
            ])
            ->add('place', EntityType::class, [
                'class' => Place::class,
                'choice_label' => 'placeName',
                'required' => false,
                'placeholder' => 'Sélectionnez un lieu',
                'label' => 'Lieu',
                'attr' => [
                    'class' => 'form-control rounded-lg'
                ]
            ])
        ;
//SLB : remplacé par enregistrer et publier qui sont dans create twig
//            ->add('submit', SubmitType::class, [
//                'label' => 'Créer la sortie',
//                'attr' => ['class' => 'btn btn-success mt-3 mb-3 rounded-lg w-100']
//            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Sortie::class,
        ]);
    }
}

templates/sortie/annuler_sortie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annuler une sortie{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h1>Annuler la sortie : {{ sortie.name }}</h1>

        <form method="post">
            <div class="mb-3">
                <label for="motif">Motif d'annulation :</label>
                <textarea name="motif" id="motif" class="form-control" required></textarea>
            </div>
            <button type="submit" class="btn btn-danger">Confirmer l'annulation</button>
            <a href="{{ path('sortie_list') }}" class="btn btn-secondary">Retour</a>
        </form>
    </div>
{% endblock %}

templates/sortie/cancel.html.twig
{% extends 'base.html.twig' %}

{% block title %}Annuler la sortie : {{ sortie.name }}{% endblock %}
{% form_theme form 'bootstrap_5_layout.html.twig' %}

{% block body %}
    <div class="container mt-5">
        <h1 class="text-center mb-4">Annuler une sortie</h1>
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6">
                <p>Veuillez confirmer l'annulation de la sortie **{{ sortie.name }}** et en indiquer la raison :</p>

                {{ form_start(form) }}
                {{ form_widget(form) }}
                <div class="d-flex justify-content-between mt-3">
                    <button type="submit" class="btn btn-danger">Confirmer l'annulation</button>
                    <a href="{{ path('sortie_detail', {'id': sortie.id}) }}" class="btn btn-secondary">Retour à la sortie</a>
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/sortie/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créer une nouvelle sortie{% endblock %}

{% block body %}
    <div class="container mt-5 mb-5">
        <h1 class="text-center mb-4">✨ Créer une nouvelle sortie</h1>
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6">
                <div>
                    {{ form_start(sortie_form) }}

                    {{ form_row(sortie_form.name) }}
                    {{ form_row(sortie_form.startDatetime) }}
                    {{ form_row(sortie_form.duration) }}
                    {{ form_row(sortie_form.registrationDeadline) }}
                    {{ form_row(sortie_form.maxRegistrations) }}
                    {{ form_row(sortie_form.description) }}
                    {{ form_row(sortie_form.photoUrl) }}


                    <div class="d-flex align-items-center justify-content-between">
                        {{ form_row(sortie_form.place) }}
                        <button type="button" class="btn btn-outline-primary ms-2" data-bs-toggle="modal"
                                data-bs-target="#addPlaceModal">
                            Ajouter un lieu
                        </button>
                    </div>

                    <div class="d-flex justify-content-between mt-3">
                        <button type="submit" name="save" class="btn btn-secondary w-48">Enregistrer</button>
                        <button type="submit" name="publish" class="btn btn-success w-48">Publier</button>
                    </div>


                    {{ form_end(sortie_form) }}

                </div>
            </div>

            {# MODAL DE CRÉATION DE LIEU #}
            <div class="modal fade" id="addPlaceModal" tabindex="-1" aria-labelledby="addPlaceModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <form id="placeForm" class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="addPlaceModalLabel">Ajouter un nouveau lieu</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Fermer"></button>
                        </div>
                        <div class="modal-body">
                            <input type="hidden" name="_token" value="{{ csrf_token('place_creation') }}">
                            <div class="mb-3">
                                <label for="place_name" class="form-label">Nom du lieu</label>
                                <input type="text" class="form-control" id="place_name" name="name" required>
                            </div>
                            <div class="mb-3">
                                <label for="place_city" class="form-label">Ville</label>
                                <select class="form-select" id="place_city" name="city" required>
                                    {% for city in cities %}
                                        <option value="{{ city.id }}">{{ city.cityName }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="mb-3">
                                <label for="place_address" class="form-label">Adresse</label>
                                <input type="text" class="form-control" id="place_address" name="address" required>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-primary">Enregistrer</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>

    <script>
        document.getElementById('placeForm').addEventListener('submit', function (event) {
            event.preventDefault();

            const form = this;
            const formData = new FormData(form);

            fetch('{{ path('place_create_ajax') }}', {
                method: 'POST',
                body: formData,
                headers: {
                    'X-Requested-With': 'XMLHttpRequest'
                }
            })
                .then(response => response.json())
                .then(data => {
                    if (data.success && data.place) {
                        const placeSelect = document.getElementById('{{ sortie_form.place.vars.id }}');
                        const newOption = document.createElement('option');
                        newOption.value = data.place.id;
                        newOption.textContent = `${data.place.name} (${data.place.city})`;
                        newOption.selected = true;
                        placeSelect.appendChild(newOption);

                        bootstrap.Modal.getInstance(document.getElementById('addPlaceModal')).hide();
                        form.reset();
                    } else {
                        alert(data.error || 'Erreur inconnue lors de l\'ajout du lieu.');
                    }
                })
                .catch(error => {
                    console.error('Erreur AJAX :', error);
                    alert('Une erreur est survenue lors de la requête.');
                });
        });
    </script>

{% endblock %}

templates/sortie/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail de la sortie : {{ sortie.name }}{% endblock %}

{% block body %}

    <div class="container mt-4 mb-5">
        <h1 class="text-center mb-4">Détails de sortie</h1>

        <div class="row">
            <div class="col-md-6">
                <p><strong>Nom de la sortie :</strong> {{ sortie.name }}</p>
                <p><strong>Date et heure de la sortie :</strong> {{ sortie.startDatetime ? sortie.startDatetime|date('d/m/Y H:i') : '—' }}</p>
                <p><strong>Date limite d'inscription :</strong> {{ sortie.registrationDeadline ? sortie.registrationDeadline|date('d/m/Y H:i') : '—' }}</p>
                <p><strong>Nombre de places occupées :</strong> {{ sortie.users.count }} / {{ sortie.maxRegistrations }}</p>
                <p><strong>Durée :</strong> {{ sortie.duration }} minutes</p>
                <p><strong>Description et infos :</strong> {{ sortie.description }}</p>
            </div>

            <div class="col-md-6">
                <p><strong>Campus organisateur :</strong> {{ sortie.campus.campusName }}</p>
                <p><strong>Lieu :</strong> {{ sortie.place.placeName }}</p>
                <p><strong>Rue :</strong> {{ sortie.place.street }}</p>
                <p><strong>Code postal :</strong> {{ sortie.place.city.postalCode }}</p>
                <p><strong>Latitude :</strong> {{ sortie.place.latitude }}</p>
                <p><strong>Longitude :</strong> {{ sortie.place.longitude }}</p>
                <div class="mt-3" style="width: 100%; height: 300px;">
                    <iframe
                        width="100%"
                        height="100%"
                        style="border:0"
                        src="https://maps.google.com/maps?q={{ sortie.place.latitude }},{{ sortie.place.longitude }}&z=15&output=embed"
                        allowfullscreen
                    ></iframe>
                </div>
            </div>
        </div>

        <hr class="my-4">

        <h2>Liste des utilisateurs inscrits :</h2>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead class="thead-dark">
                <tr>
                    <th>Pseudo</th>
                    <th>Nom</th>
                </tr>
                </thead>
                <tbody>
                {% for user in sortie.users %}
                    <tr>
                        <td>{{ user.pseudo }}</td>
                        <td>{{ user.firstName }} {{ user.lastName }}</td>
                    </tr>
                {% else %}
                    <tr>
                        <td colspan="2" class="text-center">Aucun user n'est encore inscrit.</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        {% if is_organizer and sortie.status.statusLabel == 'Créée' %}
            <a href="{{ path('sortie_edit', {'id': sortie.id}) }}" class="btn btn-info mt-3">Modifier la sortie</a>
            <form action="{{ path('sortie_publish', {'id': sortie.id}) }}" method="post" class="d-inline">
                <button type="submit" class="btn btn-success mt-3">Publier la sortie</button>
            </form>
        {% endif %}

        {% if is_organizer and sortie.startDatetime > "now"|date and sortie.status.statusLabel in ['Créée', 'Ouverte', 'Fermée'] %}
            <a href="{{ path('sortie_cancel', {'id': sortie.id}) }}" class="btn btn-danger mt-3">Annuler la sortie</a>
        {% endif %}

        {% if not is_organizer and is_registration_open %}
            {% if is_full %}
                <p class="alert alert-warning mt-3">Cette sortie est complète ! </p>
            {% elseif not is_registered %}
                <a href="{{ path('sortie_register', {'id': sortie.id}) }}" class="btn btn-success mt-3">S'inscrire à cette sortie</a>
            {% elseif is_registered %}
                <a href="{{ path('sortie_unregister', {'id': sortie.id}) }}" class="btn btn-warning mt-3">Se désinscrire</a>
            {% endif %}
        {% endif %}

        <a href="{{ path('sortie_list') }}" class="btn btn-secondary mt-3">Retour à la liste</a>
    </div>
{% endblock %}

templates/sortie/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la sortie{% endblock %}
{% form_theme sortie_form 'bootstrap_5_layout.html.twig' %}

{% block body %}
    <div class="container mt-5">
        <h1 class="text-center mb-4">✍️ Modifier une sortie</h1>
        <div class="row justify-content-center">
            <div class="col-md-8 col-lg-6">
                {{ form_start(sortie_form, {'action': path('sortie_edit', {'id': sortie.id})}) }}
                {{ form_row(sortie_form.name) }}
                {{ form_row(sortie_form.startDatetime) }}
                {{ form_row(sortie_form.duration) }}
                {{ form_row(sortie_form.registrationDeadline) }}
                {{ form_row(sortie_form.maxRegistrations) }}
                {{ form_row(sortie_form.description) }}
                {{ form_row(sortie_form.photoUrl) }}

                <div class="mb-3">
                    {{ form_label(sortie_form.place) }}
                    <div class="input-group">
                        {{ form_widget(sortie_form.place, {'attr': {'class': 'form-select'}}) }}
                        <a href="{{ path('app_place_new') }}" class="btn btn-primary" style="margin-left: 10px;">
                            Ajouter un lieu
                        </a>
                    </div>
                    {{ form_errors(sortie_form.place) }}
                </div>

                <div class="d-flex justify-content-between mt-3">
                    <button type="submit" name="save" class="btn btn-secondary w-48">Enregistrer</button>
                    <button type="submit" name="publish" class="btn btn-success w-48">Publier</button>
                </div>

                <a href="{{ path('sortie_detail', {'id': sortie.id}) }}" class="btn btn-link mt-3 text-center w-100">Annuler</a>

                {{ form_end(sortie_form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/sortie/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Sorties{% endblock %}

{% block body %}

<div class="container mt-4">
    <h1 class="mb-4">Sorties disponibles</h1>

        {% if app.user %}
            {{ form_start(form) }}
            <div class="row g-3">
                {% for field in form %}
                    <div class="col-md-4">
                        {{ form_row(field) }}
                    </div>
                {% endfor %}
                <div>
                    <div class="col-md-4 d-flex align-items-end">
                    <button type="submit" class="btn btn-primary">Rechercher</button>
                </div>
            </div>
            {{ form_end(form) }}
        {% endif %}

        {% if is_granted('ROLE_ADMIN') %}
            <form action="{{ path('sortie_archive') }}" method="post" class="d-inline-flex">
                <button type="submit" class="btn btn-info ms-3">Archiver</button>
            </form>
        {% endif %}
    </div>
</div>

    <div class="container mt-5">
        <div class="row">
            {% for sortie in sorties %}
                <div class="col-md-6 col-lg-4 mb-4">
                    <a href="{{ path('sortie_detail', {'id': sortie.id}) }}" class="text-decoration-none">
                        <div class="card h-100 shadow-sm text-white border-0"
                             style="background-image: url('{{ sortie.photoUrl ? asset('uploads/pictures/sorties/' ~ sortie.photoUrl) : asset('images/default.jpg') }}');
                                 background-size: cover;
                                 background-position: center;">
                            <div class="card-body bg-dark bg-opacity-50 d-flex flex-column">
                                <h5 class="card-title">{{ sortie.name }}</h5>
                                <p class="card-text mb-1">
                                    <strong>Campus :</strong> {{ sortie.campus.campusName }}

                                </p>
                                <p class="card-text mb-1">
                                    <strong>Date :</strong>
                                    {{ sortie.startDatetime ? sortie.startDatetime|date('d/m/Y H:i') : '—' }}
                                </p>
                                <p class="card-text mb-1">
                                    <strong>Durée :</strong> {{ sortie.duration }} min
                                </p>

                                <p class="card-text mb-1">
                                    <strong>Lieu :</strong> {{ sortie.place }}
                                </p>
                                <p class="card-text mb-0">
                                    <strong>Organisateur :</strong> {{ sortie.organizer }}
                                </p>
                                <p class="card-text mb-0">
                                    <strong>Statut :</strong> {{ sortie.status.statusLabel }}
                                </p>
                                {% if is_granted('ROLE_ADMIN') and sortie.organizer != app.user and sortie.status.id != 6 %}
                                    <a href="{{ path('sortie_annuler', {'id': sortie.id}) }}"
                                       class="btn btn-warning btn-sm mt-2"
                                       onclick="return confirm('Confirmer l\'annulation de cette sortie ?');">
                                        🛑 Annuler
                                    </a>
                                {% endif %}


                            </div>
                        </div>
                    </a>
                </div>
            {% else %}
                <div class="col-12">
                    <div class="alert alert-info text-center">
                        Aucune sortie disponible.
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}